### PR TITLE
Add pause interval to shop refreshes

### PR DESCRIPTION
**Pull request by chrisli-03**
Hi sorry I deleted the wrong repo on github, remade a pr

### CODE REVIEW

**Comment by Unovamata** [comment]
No worries! Thank you for your hard work! 😄 

I am quite busy this week, so I will try to find a space in my schedule to merge the pull request, but so far it looks great! You are the best!

**Review by Unovamata — CHANGES_REQUESTED** [review]
You did a great job! Thank you very much for your contribution!  This has been a very sought after feature in the extension, so many users will be thankful for this change!

I do have an improvement I would like to suggest before merging, in the "optionsPage.js" script, could you format the jQuery bind function like the ones at the bottom?

This is because the format referenced is leftover code from the original version of the extension, the original code was obfuscated and quite messy. I would like for new feature implementations to align with the following format:

**For example:** 

**Setter:**
```
function setVARIABLE_NAME(value) { chrome.storage.local.set({ VARIABLE_NAME: value }, (function () {})) }
```

**jQuery Call to GUI (This usually changes based on the input/output value):**
```
$("#VARIABLE_NAME").bind("input propertychange", (function() {
    setVARIABLE_NAME($("#VARIABLE_NAME").val())
}))
```

**Reset Button Destructuring:**
```
VARIABLE_NAME: 0.75,
```

**Send to GUI After Destructuring:**
```
$("#VARIABLE_NAME").val(_.VARIABLE_NAME),
```

This format allows me to more visually identify distinct elements in the GUI and their interaction with "optionsPage.js." You did a wonderful job! Thank you so very much for your PR!

**Comment by chrisli-03** [comment]
> You did a great job! Thank you very much for your contribution! This has been a very sought after feature in the extension, so many users will be thankful for this change!
> 
> I do have an improvement I would like to suggest before merging, in the "optionsPage.js" script, could you format the jQuery bind function like the ones at the bottom?
> 
> This is because the format referenced is leftover code from the original version of the extension, the original code was obfuscated and quite messy. I would like for new feature implementations to align with the following format:
> 
> **For example:**
> 
> **Setter:**
> 
> ```
> function setVARIABLE_NAME(value) { chrome.storage.local.set({ VARIABLE_NAME: value }, (function () {})) }
> ```
> 
> **jQuery Call to GUI (This usually changes based on the input/output value):**
> 
> ```
> $("#VARIABLE_NAME").bind("input propertychange", (function() {
>     setVARIABLE_NAME($("#VARIABLE_NAME").val())
> }))
> ```
> 
> **Reset Button Destructuring:**
> 
> ```
> VARIABLE_NAME: 0.75,
> ```
> 
> **Send to GUI After Destructuring:**
> 
> ```
> $("#VARIABLE_NAME").val(_.VARIABLE_NAME),
> ```
> 
> This format allows me to more visually identify distinct elements in the GUI and their interaction with "optionsPage.js." You did a wonderful job! Thank you so very much for your PR!

I updated the format, could you check if its what you are looking for? Thank you

**Comment by Unovamata** [comment]
I have reviewed and fixed the conflicts the current commit had with the new additions of the extension. It works perfectly now! Thank you very much for your hard work! I did not expected you to format the entire options script in the format I needed. Still, I am super grateful for it!

Thank you very much for your support and contribution! I will make sure to credit you in the extension's miscellaneous page. It was a pleasure working with you. 😄

**Comment by Unovamata** [comment]
The commit https://github.com/Unovamata/Neopets-Shop-And-Attic-Autobuyer-Cracked/commit/9e192547d06e2fd0dff972c0d14614936113b6d8, has improved some aspects of the wait times set by the "PauseBetweenMinutes" system, as this can cause slowdowns for users not utilizing pauses.

Now the system returns the "notPaused" variable early, since every millisecond counts, this has been done to save in processing power. At the same time, this is a good programming practice to avoid nesting as much as possible.

Thank you very much for your contribution! I will be updating any further changes done to this PR in the future. 😄

**Pull request merged**
